/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardAttendanceRouteImport } from './routes/_dashboard.attendance'
import { Route as DashboardRecordingsRouteImport } from './routes/_dashboard.recordings'
import { Route as DashboardSessionsRouteImport } from './routes/_dashboard.sessions'
import { Route as DashboardStudentDashboardRouteImport } from './routes/_dashboard.student-dashboard'
import { Route as DashboardTeacherDashboardRouteImport } from './routes/_dashboard.teacher-dashboard'
import { Route as SiteIndexRouteImport } from './routes/_site.index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordingsRoute = DashboardRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsRoute = DashboardSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentDashboardRoute =
  DashboardStudentDashboardRouteImport.update({
    id: '/student-dashboard',
    path: '/student-dashboard',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeacherDashboardRoute =
  DashboardTeacherDashboardRouteImport.update({
    id: '/teacher-dashboard',
    path: '/teacher-dashboard',
    getParentRoute: () => DashboardRoute,
  } as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/attendance': typeof DashboardAttendanceRoute
  '/recordings': typeof DashboardRecordingsRoute
  '/sessions': typeof DashboardSessionsRoute
  '/student-dashboard': typeof DashboardStudentDashboardRoute
  '/teacher-dashboard': typeof DashboardTeacherDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/attendance': typeof DashboardAttendanceRoute
  '/recordings': typeof DashboardRecordingsRoute
  '/sessions': typeof DashboardSessionsRoute
  '/student-dashboard': typeof DashboardStudentDashboardRoute
  '/teacher-dashboard': typeof DashboardTeacherDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_dashboard/attendance': typeof DashboardAttendanceRoute
  '/_dashboard/recordings': typeof DashboardRecordingsRoute
  '/_dashboard/sessions': typeof DashboardSessionsRoute
  '/_dashboard/student-dashboard': typeof DashboardStudentDashboardRoute
  '/_dashboard/teacher-dashboard': typeof DashboardTeacherDashboardRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/attendance'
    | '/recordings'
    | '/sessions'
    | '/student-dashboard'
    | '/teacher-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/attendance'
    | '/recordings'
    | '/sessions'
    | '/student-dashboard'
    | '/teacher-dashboard'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_site'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_dashboard/attendance'
    | '/_dashboard/recordings'
    | '/_dashboard/sessions'
    | '/_dashboard/student-dashboard'
    | '/_dashboard/teacher-dashboard'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/attendance': {
      id: '/_dashboard/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/recordings': {
      id: '/_dashboard/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof DashboardRecordingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sessions': {
      id: '/_dashboard/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof DashboardSessionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/student-dashboard': {
      id: '/_dashboard/student-dashboard'
      path: '/student-dashboard'
      fullPath: '/student-dashboard'
      preLoaderRoute: typeof DashboardStudentDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/teacher-dashboard': {
      id: '/_dashboard/teacher-dashboard'
      path: '/teacher-dashboard'
      fullPath: '/teacher-dashboard'
      preLoaderRoute: typeof DashboardTeacherDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardRecordingsRoute: typeof DashboardRecordingsRoute
  DashboardSessionsRoute: typeof DashboardSessionsRoute
  DashboardStudentDashboardRoute: typeof DashboardStudentDashboardRoute
  DashboardTeacherDashboardRoute: typeof DashboardTeacherDashboardRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardRecordingsRoute: DashboardRecordingsRoute,
  DashboardSessionsRoute: DashboardSessionsRoute,
  DashboardStudentDashboardRoute: DashboardStudentDashboardRoute,
  DashboardTeacherDashboardRoute: DashboardTeacherDashboardRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SiteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
